"""Clinical report generation utilities for SpectiqAI."""

from __future__ import annotations

from pathlib import Path
from fpdf import FPDF


class ClinicalReportPDF(FPDF):
    """Subclass FPDF to implement standard layouts like headers and footers."""

    def footer(self) -> None:
        # Position at 1.2 cm from bottom
        self.set_y(-12)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(148, 163, 184)  # Professional muted slate gray
        
        # Left-aligned brand, right-aligned page number
        self.cell(100, 10, "Generated by SpectiqAI Diagnostics Research Platform", border=0, align="L")
        self.cell(0, 10, f"Page {self.page_no()}", border=0, align="R")


def create_clinical_pdf(
    output_path: Path,
    original_path: Path,
    heatmap_path: Path,
    overlay_path: Path,
    metadata: dict
) -> None:
    """
    Generate a professional clinical diagnostic report PDF containing 11 required elements:
    1. Patient Scan Preview
    2. Prediction Result
    3. Confidence
    4. Confidence Category
    5. Model Used
    6. Timestamp
    7. Inference Time
    8. Grad-CAM Visualization
    9. Explainability Summary
    10. Dataset Information
    11. System Version

    Footer: "Generated by SpectiqAI Diagnostics Research Platform"
    """
    # Create custom FPDF document
    pdf = ClinicalReportPDF(orientation="P", unit="mm", format="A4")
    pdf.set_margins(10, 10, 10)
    pdf.add_page()
    
    # 1. Header block
    pdf.set_font("helvetica", "B", 18)
    pdf.set_text_color(30, 41, 59)  # Dark slate gray
    pdf.cell(0, 8, "SpectiqAI Clinical Research Report", new_x="LMARGIN", new_y="NEXT", align="L")
    
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(100, 116, 139)  # Light slate gray
    pdf.cell(0, 5, "Hyperspectral-Derived Kidney Tissue Diagnostic Classification & Interpretability Analysis", new_x="LMARGIN", new_y="NEXT", align="L")
    pdf.ln(3)
    
    # Horizontal line
    pdf.set_draw_color(226, 232, 240)  # Border gray
    pdf.line(10, 26, 200, 26)
    pdf.ln(4)
    
    # 2. Section 1: Metadata Table
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(51, 65, 85)
    pdf.cell(0, 6, "1. System & Acquisition Metadata", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)
    
    # Set styling for table headers
    pdf.set_font("helvetica", "B", 8.5)
    pdf.set_fill_color(248, 250, 252)  # Very light gray
    pdf.set_draw_color(241, 245, 249)
    
    # Row 1: Scan File & Timestamp
    pdf.cell(45, 6, "Uploaded Scan File", border=1, fill=True)
    pdf.set_font("helvetica", "", 8.5)
    pdf.cell(50, 6, str(metadata.get("filename", "N/A")), border=1)
    pdf.set_font("helvetica", "B", 8.5)
    pdf.cell(45, 6, "Analysis Timestamp", border=1, fill=True)
    pdf.set_font("helvetica", "", 8.5)
    pdf.cell(50, 6, str(metadata.get("timestamp", "N/A")), border=1, new_x="LMARGIN", new_y="NEXT")
    
    # Row 2: Model & System Version
    pdf.set_font("helvetica", "B", 8.5)
    pdf.cell(45, 6, "Model Architecture", border=1, fill=True)
    pdf.set_font("helvetica", "", 8.5)
    pdf.cell(50, 6, str(metadata.get("model_name", "N/A")), border=1)
    pdf.set_font("helvetica", "B", 8.5)
    pdf.cell(45, 6, "System Software Version", border=1, fill=True)
    pdf.set_font("helvetica", "", 8.5)
    pdf.cell(50, 6, str(metadata.get("system_version", "v1.2.0 (Research Mode)")), border=1, new_x="LMARGIN", new_y="NEXT")

    # Row 3: Image Validation & Latency
    pdf.set_font("helvetica", "B", 8.5)
    pdf.cell(45, 6, "Image Validation Status", border=1, fill=True)
    pdf.set_font("helvetica", "", 8.5)
    val_status = "PASSED (OOD Check)" if metadata.get("validation_passed", True) else "FAILED (OOD Check)"
    pdf.cell(50, 6, val_status, border=1)
    pdf.set_font("helvetica", "B", 8.5)
    pdf.cell(45, 6, "Inference Latency", border=1, fill=True)
    pdf.set_font("helvetica", "", 8.5)
    pdf.cell(50, 6, f"{metadata.get('latency', 0.0):.4f} seconds", border=1, new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(5)
    
    # 3. Section 2: Prediction Results
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(51, 65, 85)
    pdf.cell(0, 6, "2. Model Diagnostic Prediction & Confidence", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)
    
    prediction = metadata.get("prediction", "N/A")
    confidence = metadata.get("confidence", 0.0)
    conf_category = metadata.get("confidence_category", "N/A")
    conf_explanation = metadata.get("confidence_explanation", "")
    tumor_prob = metadata.get("tumor_probability", 0.0)
    normal_prob = metadata.get("normal_probability", 0.0)
    
    # Style background based on diagnostic state
    if prediction == "Tumor":
        pdf.set_fill_color(254, 242, 242)  # Light Red
        pdf.set_text_color(153, 27, 27)    # Dark Red
        border_color = (252, 165, 165)
    elif prediction == "Normal":
        pdf.set_fill_color(240, 253, 250)  # Light Teal/Green
        pdf.set_text_color(17, 94, 89)     # Dark Teal
        border_color = (153, 246, 228)
    else:
        pdf.set_fill_color(255, 251, 235)  # Light Amber/Yellow
        pdf.set_text_color(180, 83, 9)     # Dark Amber
        border_color = (252, 211, 77)
        
    pdf.set_draw_color(*border_color)
    pdf.set_font("helvetica", "B", 11)
    
    # Banner showing status, raw confidence and category
    banner_text = f"  STATUS: {prediction.upper()}  |  CONFIDENCE: {confidence:.2%} ({conf_category})"
    pdf.cell(0, 10, banner_text, border=1, fill=True, new_x="LMARGIN", new_y="NEXT")
    
    # Probability Row + Explanation
    pdf.set_text_color(51, 65, 85)
    pdf.set_draw_color(226, 232, 240)
    pdf.set_font("helvetica", "", 8.5)
    pdf.ln(2)
    pdf.cell(95, 6, f" Tumor Probability: {tumor_prob:.2%}", border=1)
    pdf.cell(95, 6, f" Normal Probability: {normal_prob:.2%}", border=1, new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "I", 8.5)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(0, 6, f"Clinical Guidance: {conf_explanation}", border=0, new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(4)
    
    # 4. Section 3: Visual Interpretability
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(51, 65, 85)
    pdf.cell(0, 6, "3. Visual Explainability (Grad-CAM Outline)", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 8.5)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 4, "Localization maps highlighting localized tissue regions that contributed to the classification.", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    
    # Embed the three images side-by-side
    img_w = 58
    img_h = 58
    y_pos = pdf.get_y()
    
    # Embed image paths
    pdf.image(str(original_path), x=10, y=y_pos, w=img_w, h=img_h)
    pdf.image(str(heatmap_path), x=76, y=y_pos, w=img_w, h=img_h)
    pdf.image(str(overlay_path), x=142, y=y_pos, w=img_w, h=img_h)
    
    pdf.set_y(y_pos + img_h + 2)
    pdf.set_font("helvetica", "B", 8)
    pdf.set_text_color(51, 65, 85)
    pdf.cell(img_w, 4, "1. Patient Scan Preview", align="C")
    pdf.cell(8, 4, "")
    pdf.cell(img_w, 4, "2. Activation Heatmap", align="C")
    pdf.cell(8, 4, "")
    pdf.cell(img_w, 4, "3. Blended Overlay", align="C", new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(4)
    
    # 5. Section 4: Explainability Summary
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(0, 6, "4. Explainability Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 8.5)
    pdf.set_text_color(51, 65, 85)
    expl_summary = metadata.get(
        "explainability_summary",
        "The model primarily focused on central renal tissue structures. Highest activation regions are highlighted in red and orange."
    )
    pdf.multi_cell(0, 4, expl_summary, border=0, align="L")
    pdf.ln(4)
    
    # 6. Section 5: Dataset & Training Information
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(0, 6, "5. Dataset & Methodology Reference", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_fill_color(248, 250, 252)
    pdf.set_draw_color(226, 232, 240)
    pdf.set_font("helvetica", "", 8)
    pdf.set_text_color(71, 85, 105)
    
    dataset_details = (
        "Dataset Source: Hyper and Multispectral Kidney Image Dataset | "
        "Total Sample Count: 10,000 scans (5,000 Tumor, 5,000 Normal)\n"
        "Stratified Partition splits: 70% Training (7,000), 15% Validation (1,500), 15% Testing (1,500) | "
        "Input Dimensions: 224 x 224 pixels\n"
        "Simple CNN Architecture: 4 Conv-BatchNorm-ReLU-MaxPool blocks with Adaptive Average Pooling (98,178 parameters)"
    )
    pdf.multi_cell(0, 4, dataset_details, border=1, fill=True, align="L")
    pdf.ln(4)
    
    # 7. Section 6: Clinical Disclaimer Box
    pdf.set_font("helvetica", "B", 7.5)
    pdf.set_text_color(100, 116, 139)
    pdf.set_fill_color(254, 254, 254)
    pdf.set_draw_color(241, 245, 249)
    disclaimer_text = (
        "RESEARCH PROTOTYPE EVALUATION DISCLAIMER: This document is a computer-generated diagnostic classification report "
        "created by the SpectiqAI clinical decision-support research prototype for final year project demonstration purposes. "
        "This system is not approved for patient diagnosis, surgical planning, or real-time clinical intervention. All visual "
        "maps are generated dynamically to explain classifier weight distributions and must be verified pathologically."
    )
    pdf.multi_cell(0, 3.5, disclaimer_text, border=1, fill=True, align="L")
    
    # Write to disk
    pdf.output(str(output_path))
